version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vi_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: vi_user
      POSTGRES_PASSWORD: vi_password
      POSTGRES_DB: vi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vi_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vi_redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vi_backend
    ports:
      - "8101:8100"
    environment:
      DATABASE_URL: postgresql://vi_user:vi_password@postgres:5432/vi_db
      REDIS_URL: redis://redis:6379
      API_PORT: 8100
    volumes:
      - ./backend:/app
      - /Users/wojciechwiesner/ai:/ai_projects:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn src.main:app --host 0.0.0.0 --port 8100 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api/v1
    container_name: vi_frontend
    ports:
      - "3101:80"
    environment:
      VITE_API_URL: http://localhost:8101/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
