version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zenith_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: zenith
      POSTGRES_PASSWORD: zenith
      POSTGRES_DB: zenith_coder
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zenith"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: zenith_redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zenith_backend
    ports:
      - "8100:8100"
    environment:
      DATABASE_URL: postgresql://zenith:zenith@postgres:5432/zenith_coder
      REDIS_URL: redis://redis:6379
      API_PORT: 8100
    volumes:
      - ./backend:/app
      - /Users/wojciechwiesner/ai:/ai_projects:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn src.main:app --host 0.0.0.0 --port 8100 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zenith_frontend
    ports:
      - "3100:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8100
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: